name: Build and Lint
on:
  push:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint
      - run: echo "${{toJson(github)}}"
